import React from 'react'
import { Document, Page, View, Text, StyleSheet } from '@react-pdf/renderer'
import type { Profile } from '@/src/types/profile'
import type { Credential } from '@/src/types/credential'

const styles = StyleSheet.create({
  page: { padding: 24, fontSize: 11, fontFamily: 'Helvetica' },
  header: { marginBottom: 8 },
  name: { fontSize: 18, fontWeight: 700 },
  headline: { fontSize: 12, marginBottom: 8, color: '#0F766E' },
  section: { marginTop: 8, marginBottom: 4 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginBottom: 4 },
  text: { fontSize: 10, marginBottom: 2 },
  credentialRow: { marginBottom: 6 },
  smallMuted: { fontSize: 9, color: '#64748B' },
})

export interface CVDocumentProps {
  profile: Profile
  credentials?: Credential[]
}

export function CVDocument({ profile, credentials = [] }: CVDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.name}>{profile.full_name ?? 'No name'}</Text>
          {profile.headline ? <Text style={styles.headline}>{profile.headline}</Text> : null}
          {profile.location ? <Text style={styles.smallMuted}>{profile.location}</Text> : null}
        </View>

        {profile.bio ? (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>About</Text>
            <Text style={styles.text}>{profile.bio}</Text>
          </View>
        ) : null}

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Credentials</Text>
          {credentials.length === 0 ? (
            <Text style={styles.text}>No credentials listed.</Text>
          ) : (
            credentials.map((c) => (
              <View key={c.id} style={styles.credentialRow}>
                <Text style={{ fontSize: 11, fontWeight: 600 }}>{c.title}</Text>
                <Text style={styles.smallMuted}>{c.institution_name}</Text>
                <Text style={styles.smallMuted}>
                  {c.issue_date}{c.expiry_date ? ` — ${c.expiry_date}` : ''}
                </Text>
              </View>
            ))
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Generated by MyMzansi Skills</Text>
          <Text style={styles.smallMuted}>Clean one-page export — optimized for printing and sharing.</Text>
        </View>
      </Page>
    </Document>
  )
}

export default CVDocument
