import type { Metadata } from "next";
import "./globals.css";
import "tailwindcss";
import { Toaster } from 'react-hot-toast'
import { cn } from '../lib/utils'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('h-full antialiased')}>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700&family=IBM+Plex+Mono:wght@400;600&display=swap" rel="stylesheet" />
      </head>
      <body className={cn('min-h-full flex flex-col')}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
